# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160205_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre de Usuario'),
        ),
    ]
